name: Dependabot auto approve and merge
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-approve:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.5
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Comment about dependabot auto merge
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Szevasz - ${{ github.event.number }}
            Updated dependencies: ${{steps.dependabot-metadata.outputs.dependency-names}}
            Type: ${{steps.dependabot-metadata.outputs.dependency-type}}
            Type: ${{steps.dependabot-metadata.outputs.dependency-type}}
            Update Type: ${{steps.dependabot-metadata.outputs.update-type}}

            ${{steps.dependabot-metadata.outputs.previous-version}} --> ${{steps.dependabot-metadata.outputs.new-version}}
          reactions: heart, hooray, laugh
      - name: Add a label for all production dependencies
        run: gh pr edit "$PR_URL" --add-label "auto-merged"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
